// app/api/analyze/route.js
// API de análisis pre-game / histórico.
// Devuelve un resumen (summary) y una lista de partidos analizados (analyzed).

export async function GET() {
  const data = {
    ok: true,
    summary: {
      games: 10,
      k_used: 1,
      MAE: 2.65,
      MSE: 7.275,
    },
    analyzed: [
      {
        gameId: 1,
        date: "2024-10-21",
        matchup: "Lakers @ Nuggets",
        lineOpen: 224.5,
        lineClose: 226,
        finalTotal: 228,
        predicted: 226,
        marketMove: 1.5,
        momentum: "bullish",
        error: -2,
      },
      {
        gameId: 2,
        date: "2024-10-21",
        matchup: "Suns @ Warriors",
        lineOpen: 231.5,
        lineClose: 232,
        finalTotal: 235,
        predicted: 232,
        marketMove: 0.5,
        momentum: "neutral",
        error: -3,
      },
      {
        gameId: 3,
        date: "2024-10-22",
        matchup: "Celtics @ Heat",
        lineOpen: 219,
        lineClose: 217.5,
        finalTotal: 214,
        predicted: 217.5,
        marketMove: -1.5,
        momentum: "bearish",
        error: 3.5,
      },
      {
        gameId: 4,
        date: "2024-10-22",
        matchup: "Bucks @ Bulls",
        lineOpen: 227.5,
        lineClose: 229,
        finalTotal: 226,
        predicted: 229,
        marketMove: 1.5,
        momentum: "bullish",
        error: 3,
      },
      {
        gameId: 5,
        date: "2024-10-23",
        matchup: "Knicks @ 76ers",
        lineOpen: 221.5,
        lineClose: 220,
        finalTotal: 218,
        predicted: 220,
        marketMove: -1.5,
        momentum: "bearish",
        error: 2,
      },
      {
        gameId: 6,
        date: "2024-10-23",
        matchup: "Mavs @ Clippers",
        lineOpen: 228,
        lineClose: 230.5,
        finalTotal: 233,
        predicted: 230.5,
        marketMove: 2.5,
        momentum: "bullish",
        error: -2.5,
      },
      {
        gameId: 7,
        date: "2024-10-24",
        matchup: "Grizzlies @ Pelicans",
        lineOpen: 226.5,
        lineClose: 225,
        finalTotal: 222,
        predicted: 225,
        marketMove: -1.5,
        momentum: "bearish",
        error: 3,
      },
      {
        gameId: 8,
        date: "2024-10-24",
        matchup: "Hawks @ Raptors",
        lineOpen: 230,
        lineClose: 231.5,
        finalTotal: 229,
        predicted: 231.5,
        marketMove: 1.5,
        momentum: "bullish",
        error: 2.5,
      },
      {
        gameId: 9,
        date: "2024-10-25",
        matchup: "Cavs @ Pacers",
        lineOpen: 223.5,
        lineClose: 224,
        finalTotal: 221,
        predicted: 224,
        marketMove: 0.5,
        momentum: "neutral",
        error: 3,
      },
      {
        gameId: 10,
        date: "2024-10-25",
        matchup: "Rockets @ Spurs",
        lineOpen: 222,
        lineClose: 221,
        finalTotal: 219,
        predicted: 221,
        marketMove: -1,
        momentum: "neutral",
        error: 2,
      },
    ],
  };

  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
    },
  });
}

