// utils/fakeGames.js
// =======================================================
// Datos simulados de juegos NBA para pruebas del predictor
// =======================================================

export const fakeGames = [
  {
    id: 1,
    homeTeam: "NUG",
    awayTeam: "SUN",
    scoreHome: 58,
    scoreAway: 60,
    quarter: "Q2",
    timeLeft: "01:23",
    marketTotal: 222.5,
    marketSpread: -3.5,
    offRTG_home: 114,
    defRTG_home: 108,
    offRTG_away: 112,
    defRTG_away: 110,
    pace: 98,
    deltaLine: 0.8,
    acceleration: 1.2,
    home_injuryImpact: 2,
    away_injuryImpact: 1,
  },
  {
    id: 2,
    homeTeam: "LAL",
    awayTeam: "GSW",
    scoreHome: 70,
    scoreAway: 65,
    quarter: "Q3",
    timeLeft: "05:43",
    marketTotal: 235.5,
    marketSpread: 1.5,
    offRTG_home: 116,
    defRTG_home: 109,
    offRTG_away: 115,
    defRTG_away: 111,
    pace: 101,
    deltaLine: -0.5,
    acceleration: -1.6,
    home_injuryImpact: 3,
    away_injuryImpact: 0,
  },
  {
    id: 3,
    homeTeam: "NYK",
    awayTeam: "MIA",
    scoreHome: 44,
    scoreAway: 47,
    quarter: "Q2",
    timeLeft: "03:21",
    marketTotal: 219.5,
    marketSpread: 2.0,
    offRTG_home: 109,
    defRTG_home: 107,
    offRTG_away: 110,
    defRTG_away: 109,
    pace: 95,
    deltaLine: 1.5,
    acceleration: 1.8,
    home_injuryImpact: 1,
    away_injuryImpact: 2,
  },
];

